use crate::core::patterns::{DetectionType, Signature};

pub(crate) fn app_signatures() -> Vec<Signature> {
    vec![
        // --- CMS & Web Frameworks ---
        Signature {
            name: "Drupal 7+".to_string(),
            description: "Drupal 7/8/9 password hash".to_string(),
            pattern: r"^\$S\$[./A-Za-z0-9]{52}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("drupal7".to_string()),
            hashcat_mode: Some(7900),
            john_format: Some("drupal7".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Joomla < 2.5.18".to_string(),
            description: "Joomla MD5 salted hash".to_string(),
            pattern: r"^[a-fA-F0-9]{32}:[./A-Za-z0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("joomla".to_string()),
            hashcat_mode: Some(11),
            john_format: Some("joomla".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "vBulletin < 3.8.5".to_string(),
            description: "vBulletin MD5 salted hash".to_string(),
            pattern: r"^[a-fA-F0-9]{32}:[./A-Za-z0-9]{30}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("vbulletin".to_string()),
            hashcat_mode: Some(2611),
            john_format: Some("vbulletin".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Legacy & Misc ---
        Signature {
            name: "MSSQL 2000".to_string(),
            description: "Microsoft SQL Server 2000 hash".to_string(),
            pattern: r"^0x0100[a-fA-F0-9]{8}[a-fA-F0-9]{40}[a-fA-F0-9]{40}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("mssql2000".to_string()),
            hashcat_mode: Some(131),
            john_format: Some("mssql".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MSSQL 2005".to_string(),
            description: "Microsoft SQL Server 2005 hash".to_string(),
            pattern: r"^0x0100[a-fA-F0-9]{8}[a-fA-F0-9]{40}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("mssql2005".to_string()),
            hashcat_mode: Some(132),
            john_format: Some("mssql05".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MSSQL 2012 / 2014".to_string(),
            description: "Microsoft SQL Server 2012/2014 hash".to_string(),
            pattern: r"^0x0200[a-fA-F0-9]{8}[a-fA-F0-9]{128}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("mssql2012".to_string()),
            hashcat_mode: Some(1731),
            john_format: Some("mssql12".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Database Hashes ---
        Signature {
            name: "MySQL < 4.1".to_string(),
            description: "Old MySQL unsalted hash".to_string(),
            pattern: r"^[a-f0-9]{16}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.2, // Very short, overlaps
            common_name: Some("mysql-old".to_string()),
            hashcat_mode: Some(200),
            john_format: Some("mysql".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MySQL 4.1+ / MySQL 5".to_string(),
            description: "SHA-1(SHA-1(password))".to_string(),
            pattern: r"^\*[a-fA-F0-9]{40}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("mysql-sha1".to_string()),
            hashcat_mode: Some(300),
            john_format: Some("mysql-sha1".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "PostgreSQL".to_string(),
            description: "Postgres MD5(password + user)".to_string(),
            pattern: r"^md5[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("postgres".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Oracle 7-10g".to_string(),
            description: "Oracle DES-based hash".to_string(),
            pattern: r"^[a-fA-F0-9]{16}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.2,
            common_name: Some("oracle7".to_string()),
            hashcat_mode: Some(3100),
            john_format: Some("oracle".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Oracle 11g / 12c".to_string(),
            description: "Oracle SHA1-based salted hash".to_string(),
            pattern: r"^S:[A-Z0-9]{60}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("oracle11".to_string()),
            hashcat_mode: Some(112),
            john_format: Some("oracle11".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Web Frameworks & CMS ---
        Signature {
            name: "WordPress / phpBB (phpass)".to_string(),
            description: "Portable hash (MD5-based)".to_string(),
            pattern: r"^\$P\$[./A-Za-z0-9]{31}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("phpass".to_string()),
            hashcat_mode: Some(400),
            john_format: Some("phpass".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Django PBKDF2-SHA256".to_string(),
            description: "Django framework default hash".to_string(),
            pattern: r"^pbkdf2_sha256\$\d+\$[A-Za-z0-9+/]+\$[A-Za-z0-9+/=]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("django".to_string()),
            hashcat_mode: Some(10000),
            john_format: Some("django".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Magento 2 (SHA-256)".to_string(),
            description: "Magento 2 salted SHA-256".to_string(),
            pattern: r"^[a-fA-F0-9]{64}:[A-Za-z0-9+/]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("magento2".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Ruby on Rails (Devise)".to_string(),
            description: "Rails BCrypt-based devise hash".to_string(),
            pattern: r"^\$2[ayb]\$[0-9]{2}\$[./A-Za-z0-9]{53}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9, // Overlaps with BCrypt
            common_name: Some("rails-devise".to_string()),
            hashcat_mode: Some(3200),
            john_format: Some("bf".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Enterprise & OS ---
        Signature {
            name: "IBM RACF".to_string(),
            description: "IBM Mainframe password hash".to_string(),
            pattern: r"^[A-Z0-9]{16}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.1, // High collision
            common_name: Some("racf".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "AIX {smd5}".to_string(),
            description: "AIX salted MD5 hash".to_string(),
            pattern: r"^\{smd5\}[./A-Za-z0-9]{8}\$[./A-Za-z0-9]{22}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("aix-smd5".to_string()),
            hashcat_mode: Some(6300),
            john_format: Some("aix-smd5".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "AIX {ssha1}".to_string(),
            description: "AIX salted SHA1 hash".to_string(),
            pattern: r"^\{ssha1\}[./A-Za-z0-9]{8}\$[./A-Za-z0-9]{28}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("aix-ssha1".to_string()),
            hashcat_mode: Some(6700),
            john_format: Some("aix-ssha1".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "macOS v10.7 (Salted SHA512)".to_string(),
            description: "Legacy macOS password hash".to_string(),
            pattern: r"^[a-fA-F0-9]{136}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("macosx-sha512".to_string()),
            hashcat_mode: Some(1722),
            john_format: Some("xsha-512".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Juniper Netscreen / ScreenOS".to_string(),
            description: "Juniper local password hash".to_string(),
            pattern: r"^[A-Za-z0-9]{30}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.8,
            common_name: Some("juniper".to_string()),
            hashcat_mode: Some(22),
            john_format: Some("juniper".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Fortigate (Type 6)".to_string(),
            description: "Fortinet Type 6 encryption".to_string(),
            pattern: r"^AK1[A-Za-z0-9+/]{27}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("fortigate".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Full-Disk Encryption ---
        Signature {
            name: "BitLocker".to_string(),
            description: "Windows BitLocker encryption hash".to_string(),
            pattern: r"^\$bitlocker\$[0-9]\$[0-9]+\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("bitlocker".to_string()),
            hashcat_mode: Some(22100),
            john_format: Some("bitlocker".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "LUKS / LUKS2".to_string(),
            description: "Linux Unified Key Setup".to_string(),
            pattern: r"^\$luks\$[0-9]\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("luks".to_string()),
            hashcat_mode: Some(14600),
            john_format: Some("luks".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Apple FileVault 2".to_string(),
            description: "macOS full-disk encryption".to_string(),
            pattern: r"^\$fv2\$[0-9]+\$[a-fA-F0-9]{32}\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("filevault2".to_string()),
            hashcat_mode: Some(18300),
            john_format: Some("filevault2".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Password Managers ---
        Signature {
            name: "KeePass (KDBX)".to_string(),
            description: "KeePass Password Manager database".to_string(),
            pattern: r"^\$keepass\$[0-9]\$[0-9]+\$[0-9]+\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("keepass".to_string()),
            hashcat_mode: Some(13400),
            john_format: Some("keepass".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "1Password (Cloud)".to_string(),
            description: "1Password cloud-based vault".to_string(),
            pattern: r"^\$1password\$[0-9]\$[a-zA-Z0-9+/=]+\$[a-zA-Z0-9+/=]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("1password".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "LastPass".to_string(),
            description: "LastPass vault hash".to_string(),
            pattern: r"^[a-fA-F0-9]{64}:[a-zA-Z0-9._-]+:[0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9,
            common_name: Some("lastpass".to_string()),
            hashcat_mode: Some(6800),
            john_format: Some("lastpass".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Forensic Artifacts ---
        Signature {
            name: "Android Backup (V4)".to_string(),
            description: "Android encrypted backup format".to_string(),
            pattern: r"^\$androidbackup\$[0-9]\$[0-9]+\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("android-backup".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "iOS Backup (V1-V4)".to_string(),
            description: "Apple iTunes backup encryption".to_string(),
            pattern: r"^\$itunes_backup\$[0-9]\*[a-fA-F0-9]+\*[0-9]+\*[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("itunes-backup".to_string()),
            hashcat_mode: Some(14700),
            john_format: Some("itunes-backup".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "WhatsApp Database".to_string(),
            description: "WhatsApp encrypted database (crypt12/14/15)".to_string(),
            pattern: r"^\$whatsapp\$[0-9]+\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("whatsapp".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Crypto Wallets ---
        Signature {
            name: "MetaMask Vault".to_string(),
            description: "MetaMask browser extension wallet".to_string(),
            pattern: r"^\$metamask\$[0-9]+\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("metamask".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Electrum Wallet (Seed/Private Key)".to_string(),
            description: "Electrum Bitcoin wallet".to_string(),
            pattern: r"^\$electrum\$[0-9]\*[a-fA-F0-9]+\*[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("electrum".to_string()),
            hashcat_mode: Some(16600),
            john_format: Some("electrum".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Bitcoin Core (wallet.dat)".to_string(),
            description: "Bitcoin-Qt / Bitcoin Core wallet".to_string(),
            pattern: r"^\$bitcoin\$[0-9]+\$[a-fA-F0-9]+\$[0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("bitcoin-core".to_string()),
            hashcat_mode: Some(11300),
            john_format: Some("bitcoin".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
    ]
}
