use crate::core::patterns::{DetectionType, SecurityRating, Signature};

pub(crate) fn digest_signatures() -> Vec<Signature> {
    vec![
        // --- MDC Family ---
        Signature {
            name: "MD2".to_string(),
            description: "Message-Digest Algorithm 2".to_string(),
            pattern: r"^[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.3,
            common_name: Some("md2".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MD4".to_string(),
            description: "Message-Digest Algorithm 4".to_string(),
            pattern: r"^[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.4,
            common_name: Some("md4".to_string()),
            hashcat_mode: Some(900),
            john_format: Some("raw-md4".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MD5".to_string(),
            description: "Message-Digest Algorithm 5".to_string(),
            pattern: r"^[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9,
            common_name: Some("md5".to_string()),
            hashcat_mode: Some(0),
            john_format: Some("raw-md5".to_string()),
            security_rating: Some(SecurityRating::Broken),
            compliance_refs: vec!["PCI DSS 4.0".to_string(), "NIST SP 800-131A".to_string()],
            parameters: vec![],
        },
        // --- SHA Family ---
        Signature {
            name: "SHA-0".to_string(),
            description: "Secure Hash Algorithm 0".to_string(),
            pattern: r"^[a-fA-F0-9]{40}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.1,
            common_name: None,
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA-1".to_string(),
            description: "Secure Hash Algorithm 1".to_string(),
            pattern: r"^[a-fA-F0-9]{40}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.95,
            common_name: Some("sha1".to_string()),
            hashcat_mode: Some(100),
            john_format: Some("raw-sha1".to_string()),
            security_rating: Some(SecurityRating::Broken),
            compliance_refs: vec!["NIST FIPS 180-4".to_string()],
            parameters: vec![],
        },
        Signature {
            name: "SHA-224".to_string(),
            description: "Secure Hash Algorithm 224-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{56}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.98,
            common_name: Some("sha224".to_string()),
            hashcat_mode: Some(1300),
            john_format: Some("raw-sha224".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA-256".to_string(),
            description: "Secure Hash Algorithm 256-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.98,
            common_name: Some("sha256".to_string()),
            hashcat_mode: Some(1400),
            john_format: Some("raw-sha256".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA-384".to_string(),
            description: "Secure Hash Algorithm 384-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{96}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.98,
            common_name: Some("sha384".to_string()),
            hashcat_mode: Some(10800),
            john_format: Some("raw-sha384".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA-512".to_string(),
            description: "Secure Hash Algorithm 512-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{128}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.99,
            common_name: Some("sha512".to_string()),
            hashcat_mode: Some(1700),
            john_format: Some("raw-sha512".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- SHA-3 Family & Keccak ---
        Signature {
            name: "SHA3-224".to_string(),
            description: "SHA-3 (Keccak) 224-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{56}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.8,
            common_name: Some("sha3-224".to_string()),
            hashcat_mode: Some(17300),
            john_format: Some("raw-sha3-224".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA3-256".to_string(),
            description: "SHA-3 (Keccak) 256-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.85,
            common_name: Some("sha3-256".to_string()),
            hashcat_mode: Some(17400),
            john_format: Some("raw-sha3-256".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA3-384".to_string(),
            description: "SHA-3 (Keccak) 384-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{96}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.85,
            common_name: Some("sha3-384".to_string()),
            hashcat_mode: Some(17500),
            john_format: Some("raw-sha3-384".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA3-512".to_string(),
            description: "SHA-3 (Keccak) 512-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{128}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9,
            common_name: Some("sha3-512".to_string()),
            hashcat_mode: Some(17600),
            john_format: Some("raw-sha3-512".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Keccak-256".to_string(),
            description: "Keccak-256 (Ethereum)".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.7, // Heavy overlap with SHA3-256
            common_name: Some("keccak256".to_string()),
            hashcat_mode: Some(17700),
            john_format: Some("raw-keccak-256".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- BLAKE Family ---
        Signature {
            name: "BLAKE2b-512".to_string(),
            description: "BLAKE2b (512-bit output)".to_string(),
            pattern: r"^[a-fA-F0-9]{128}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.8,
            common_name: Some("blake2b-512".to_string()),
            hashcat_mode: Some(600),
            john_format: Some("raw-blake2b".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "BLAKE2s-256".to_string(),
            description: "BLAKE2s (256-bit output)".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.8,
            common_name: Some("blake2s-256".to_string()),
            hashcat_mode: Some(610),
            john_format: Some("raw-blake2s".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "BLAKE3".to_string(),
            description: "BLAKE3 extremely fast hash".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.6,
            common_name: Some("blake3".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- RIPEMD Family ---
        Signature {
            name: "RIPEMD-128".to_string(),
            description: "RIPE Message Digest 128-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.7,
            common_name: Some("ripemd128".to_string()),
            hashcat_mode: Some(9000),
            john_format: Some("ripemd-128".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "RIPEMD-160".to_string(),
            description: "RIPE Message Digest 160-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{40}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.7,
            common_name: Some("ripemd160".to_string()),
            hashcat_mode: Some(6000),
            john_format: Some("ripemd-160".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "RIPEMD-256".to_string(),
            description: "RIPE Message Digest 256-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.7,
            common_name: Some("ripemd256".to_string()),
            hashcat_mode: None,
            john_format: Some("ripemd-256".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "RIPEMD-320".to_string(),
            description: "RIPE Message Digest 320-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{80}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.7,
            common_name: Some("ripemd320".to_string()),
            hashcat_mode: None,
            john_format: Some("ripemd-320".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Whirlpool ---
        Signature {
            name: "Whirlpool".to_string(),
            description: "Whirlpool cryptographic hash function".to_string(),
            pattern: r"^[a-fA-F0-9]{128}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.8,
            common_name: Some("whirlpool".to_string()),
            hashcat_mode: Some(6100),
            john_format: Some("whirlpool".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- GOST Family ---
        Signature {
            name: "GOST R 34.11-94".to_string(),
            description: "GOST R 34.11-94 (Russian standard)".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.6,
            common_name: Some("gost-94".to_string()),
            hashcat_mode: Some(6900),
            john_format: Some("gost".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Streebog-256".to_string(),
            description: "GOST R 34.11-2012 (Streebog) 256-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.6,
            common_name: Some("streebog256".to_string()),
            hashcat_mode: Some(11700),
            john_format: Some("streebog-256".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Streebog-512".to_string(),
            description: "GOST R 34.11-2012 (Streebog) 512-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{128}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.6,
            common_name: Some("streebog512".to_string()),
            hashcat_mode: Some(11800),
            john_format: Some("streebog-512".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Tiger ---
        Signature {
            name: "Tiger-192".to_string(),
            description: "Tiger hash function (192-bit)".to_string(),
            pattern: r"^[a-fA-F0-9]{48}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.7,
            common_name: Some("tiger192".to_string()),
            hashcat_mode: None,
            john_format: Some("tiger".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Other Cryptographic Hashes ---
        Signature {
            name: "SM3".to_string(),
            description: "SM3 (Chinese standard hash)".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.6,
            common_name: Some("sm3".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
    ]
}
