use crate::core::patterns::{DetectionType, SecurityRating, Signature};

pub(crate) fn kdf_signatures() -> Vec<Signature> {
    vec![
        // --- Modern Password KDFs ---
        Signature {
            name: "Argon2".to_string(),
            description: "Argon2 password hash (i/d/id)".to_string(),
            pattern: r"^\$(?P<variant>argon2[di]d?)\$v=(?P<version>\d+)\$m=(?P<memory>\d+),t=(?P<time>\d+),p=(?P<parallelism>\d+)\$(?P<salt>[./A-Za-z0-9]+)\$(?P<hash>[./A-Za-z0-9]+)$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("argon2".to_string()),
            hashcat_mode: Some(11900),
            john_format: Some("argon2".to_string()),
            security_rating: Some(SecurityRating::Secure),
            compliance_refs: vec!["OWASP Password Storage".to_string()],
            parameters: vec!["variant".to_string(), "version".to_string(), "memory".to_string(), "time".to_string(), "parallelism".to_string(), "salt".to_string(), "hash".to_string()],
        },
        Signature {
            name: "BCrypt".to_string(),
            description: "Blowfish-based password hash".to_string(),
            pattern: r"^\$(?P<version>2[ayb]?)\$(?P<cost>[0-9]{2})\$(?P<salt>[./A-Za-z0-9]{22})(?P<hash>[./A-Za-z0-9]{31})$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("bcrypt".to_string()),
            hashcat_mode: Some(3200),
            john_format: Some("bf".to_string()),
            security_rating: Some(SecurityRating::Secure),
            compliance_refs: vec!["NIST SP 800-63B".to_string()],
            parameters: vec!["version".to_string(), "cost".to_string(), "salt".to_string(), "hash".to_string()],
        },
        Signature {
            name: "Scrypt".to_string(),
            description: "Scrypt key derivation function".to_string(),
            pattern: r"^\$7\$[./A-Za-z0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9,
            common_name: Some("scrypt".to_string()),
            hashcat_mode: Some(8900),
            john_format: Some("scrypt".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Unix & Linux Password Hashes ---
        Signature {
            name: "Unix Crypt (DES)".to_string(),
            description: "Traditional Unix crypt(3)".to_string(),
            pattern: r"^[./A-Za-z0-9]{13}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9,
            common_name: Some("descrypt".to_string()),
            hashcat_mode: Some(1500),
            john_format: Some("descrypt".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MD5crypt".to_string(),
            description: "MD5-based Unix crypt".to_string(),
            pattern: r"^\$1\$[./A-Za-z0-9]{8}\$[./A-Za-z0-9]{22}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("md5crypt".to_string()),
            hashcat_mode: Some(500),
            john_format: Some("md5crypt".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA256crypt".to_string(),
            description: "SHA256-based Unix crypt".to_string(),
            pattern: r"^\$5\$(?:rounds=\d+\$)?[./A-Za-z0-9]{1,16}\$[./A-Za-z0-9]{43}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("sha256crypt".to_string()),
            hashcat_mode: Some(7400),
            john_format: Some("sha256crypt".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA512crypt".to_string(),
            description: "SHA512-based Unix crypt".to_string(),
            pattern: r"^\$6\$(?:rounds=\d+\$)?[./A-Za-z0-9]{1,16}\$[./A-Za-z0-9]{86}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("sha512crypt".to_string()),
            hashcat_mode: Some(1800),
            john_format: Some("sha512crypt".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Windows Password Hashes ---
        Signature {
            name: "NTLM".to_string(),
            description: "Windows NT LAN Manager hash".to_string(),
            pattern: r"^[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.6,
            common_name: Some("ntlm".to_string()),
            hashcat_mode: Some(1000),
            john_format: Some("nt".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "NetNTLMv1 / ESS".to_string(),
            description: "Windows network authentication v1".to_string(),
            pattern: r"^[^\:]+\:[^\:]*\:[a-fA-F0-9]{16}\:[a-fA-F0-9]{48}\:[a-fA-F0-9]{48}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9,
            common_name: Some("netntlmv1".to_string()),
            hashcat_mode: Some(5500),
            john_format: Some("netntlm".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "NetNTLMv2".to_string(),
            description: "Windows network authentication v2".to_string(),
            pattern: r"^[^\:]+\:[^\:]*\:[a-fA-F0-9]{16}\:[a-fA-F0-9]{32}\:[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9,
            common_name: Some("netntlmv2".to_string()),
            hashcat_mode: Some(5600),
            john_format: Some("netntlmv2".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MS-Cash / DCC1".to_string(),
            description: "Windows Domain Cached Credentials v1".to_string(),
            pattern: r"^[A-Za-z0-9_.-]+\#[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.8,
            common_name: Some("mscash".to_string()),
            hashcat_mode: Some(1100),
            john_format: Some("mscash".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MS-Cash2 / DCC2".to_string(),
            description: "Windows Domain Cached Credentials v2".to_string(),
            pattern: r"^\$DCC2\$\d+\#[^\#]+\#[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("mscash2".to_string()),
            hashcat_mode: Some(2100),
            john_format: Some("mscash2".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Cisco Family ---
        Signature {
            name: "Cisco Type 4".to_string(),
            description: "Cisco IOS SHA256 hashing".to_string(),
            pattern: r"^\$4\$[./A-Za-z0-9]{43}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("cisco-type4".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Cisco Type 5".to_string(),
            description: "Cisco local salted MD5".to_string(),
            pattern: r"^\$1\$[./A-Za-z0-9]{4}\$[./A-Za-z0-9]{22}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("cisco-type5".to_string()),
            hashcat_mode: Some(500),
            john_format: Some("md5crypt".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Cisco Type 7".to_string(),
            description: "Cisco vigenere-based obfuscation".to_string(),
            pattern: r"^[0-9]{2}[0-9A-Fa-f]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.5,
            common_name: Some("cisco-type7".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Cisco Type 8 / 9".to_string(),
            description: "Cisco PBKDF2 / Scrypt".to_string(),
            pattern: r"^\$[89]\$[./A-Za-z0-9]{1,16}\$[./A-Za-z0-9]{43}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("cisco-type8".to_string()),
            hashcat_mode: Some(9200),
            john_format: Some("cisco8".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Enterprise & Network ---
        Signature {
            name: "Kerberos 5 TGS-REP etype 23".to_string(),
            description: "Kerberos RC4-HMAC ticket".to_string(),
            pattern: r"^\$krb5tgs\$23\$\*[^\*]*\*[^\*]*\*[^\*]*\$[a-fA-F0-9]{32}\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("krb5tgs".to_string()),
            hashcat_mode: Some(13100),
            john_format: Some("krb5tgs".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
    ]
}
