use crate::core::patterns::{DetectionType, Signature};

pub(crate) fn key_signatures() -> Vec<Signature> {
    vec![
        Signature {
            name: "WPA-PSK / WPA2-PSK".to_string(),
            description: "WIFI password hash (PMK)".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.3, // Overlaps with SHA256
            common_name: Some("wpa".to_string()),
            hashcat_mode: Some(2500),
            john_format: Some("wpapsk".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Blockchain & Crypto ---
        Signature {
            name: "Bitcoin Address (Base58Check)".to_string(),
            description: "Legacy Bitcoin address (P2PKH)".to_string(),
            pattern: r"^1[1-9A-HJ-NP-Za-km-z]{25,34}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("bitcoin-addr".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Ethereum Address".to_string(),
            description: "Ethereum wallet address (Hex)".to_string(),
            pattern: r"^0x[a-fA-F0-9]{40}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("eth-addr".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Bitcoin WIF".to_string(),
            description: "Wallet Import Format (Private Key)".to_string(),
            pattern: r"^[5KL][1-9A-HJ-NP-Za-km-z]{50,51}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("wif".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Network Protocols & IoT ---
        Signature {
            name: "EAP-MD5 / CHAP".to_string(),
            description: "Extensible Authentication Protocol MD5".to_string(),
            pattern: r"^\$chap\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("chap".to_string()),
            hashcat_mode: Some(7),
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SNMPv3".to_string(),
            description: "SNMPv3 USM authentication".to_string(),
            pattern: r"^\$snmpv3\$[0-9]\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("snmpv3".to_string()),
            hashcat_mode: Some(140),
            john_format: Some("snmpv3".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- SSH / PGP / GPG ---
        Signature {
            name: "SSH Private Key (Encrypted)".to_string(),
            description: "Encrypted OpenSSH / RSA key".to_string(),
            pattern: r"^\$pkcs8\$[0-9]\$[0-9]+\$[a-zA-Z0-9+/=]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("ssh-key".to_string()),
            hashcat_mode: Some(22911),
            john_format: Some("ssh".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "GPG / PGP Private Key".to_string(),
            description: "GNU Privacy Guard private key".to_string(),
            pattern: r"^\$gpg\$[0-9]\$[0-9]+\$[0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("gpg".to_string()),
            hashcat_mode: None,
            john_format: Some("gpg".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
    ]
}
