use crate::core::patterns::{Signature, DetectionType, SecurityRating};

pub fn get_encoding_signatures() -> Vec<Signature> {
    vec![
        Signature {
            name: "Base64".to_string(),
            description: "Base64 encoding (Standard)".to_string(),
            pattern: r"^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.7,
            common_name: Some("base64".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Base64 URL".to_string(),
            description: "Base64 encoding (URL-safe)".to_string(),
            pattern: r"^(?:[A-Za-z0-9\-_]{4})*(?:[A-Za-z0-9\-_]{2}==|[A-Za-z0-9\-_]{3}=)?$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.65,
            common_name: Some("base64url".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Base32".to_string(),
            description: "Base32 encoding (RFC 4648)".to_string(),
            pattern: r"^[A-Z2-7]{2,}=*$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.75,
            common_name: Some("base32".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Base58".to_string(),
            description: "Base58 encoding (Bitcoin style)".to_string(),
            pattern: r"^[1-9A-HJ-NP-Za-km-z]{2,}$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.6,
            common_name: Some("base58".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Hex".to_string(),
            description: "Hexadecimal encoding".to_string(),
            pattern: r"^[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.4,
            common_name: Some("hex".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "JWT".to_string(),
            description: "JSON Web Token".to_string(),
            pattern: r"^(?P<header>[A-Za-z0-9\-_]+)\.(?P<payload>[A-Za-z0-9\-_]+)\.(?P<signature>[A-Za-z0-9\-_]*)$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 1.0,
            common_name: Some("jwt".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: Some(SecurityRating::Weak), // Usually signed, but payload is just Base64
            compliance_refs: vec!["RFC 7519".to_string()],
            parameters: vec!["header".to_string(), "payload".to_string(), "signature".to_string()],
        },
        Signature {
            name: "URL Encoding".to_string(),
            description: "Percent-encoding (RFC 3986)".to_string(),
            pattern: r"^(?:%[0-9A-Fa-f]{2}|[A-Za-z0-9\-._~])+$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.3,
            common_name: Some("urlencode".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "IPv4 Address".to_string(),
            description: "Dot-decimal notation".to_string(),
            pattern: r"^(?P<oct1>25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?P<oct2>25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?P<oct3>25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?P<oct4>25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 1.0,
            common_name: Some("ipv4".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec!["oct1".to_string(), "oct2".to_string(), "oct3".to_string(), "oct4".to_string()],
        },
        Signature {
            name: "Base85 (Adobe)".to_string(),
            description: "Adobe Base85 / Ascii85".to_string(),
            pattern: r"^<~[!-z\s]+~>$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 1.0,
            common_name: Some("ascii85".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Morse Code".to_string(),
            description: "International Morse Code (./-)".to_string(),
            pattern: r"^[.\-\s/]+$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.2, // Low confidence, overlaps with simple text
            common_name: Some("morse".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Binary (0/1)".to_string(),
            description: "Binary string representation".to_string(),
            pattern: r"^[01\s]{8,}$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.3,
            common_name: Some("binary".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "HTML Entities".to_string(),
            description: "HTML character references".to_string(),
            pattern: r"&[#a-zA-Z0-9]+;".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.9,
            common_name: Some("html-entities".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Base32 & Base64 Variants ---
        Signature {
            name: "Base32 (Crockford)".to_string(),
            description: "Crockford's Base32 (no I, L, O, U)".to_string(),
            pattern: r"^[0-9A-TV-Z]{2,}$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.4,
            common_name: Some("crockford".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Base32 (z-base-32)".to_string(),
            description: "Zooko's Base32".to_string(),
            pattern: r"^[ybndrfg8ejkmcpqxot1uwisza345h76]{2,}$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.5,
            common_name: Some("zbase32".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Base64 (MIME)".to_string(),
            description: "Base64 with line breaks".to_string(),
            pattern: r"^(?:[A-Za-z0-9+/]{4}\r?\n?)*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.6,
            common_name: Some("mime-b64".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Data Serialization & Transfer ---
        Signature {
            name: "UUencode".to_string(),
            description: "Unix-to-Unix encoding".to_string(),
            pattern: r"^[\x20-\x60]+$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.1,
            common_name: Some("uuencode".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "BinHex (HQX)".to_string(),
            description: "Macintosh BinHex 4.0".to_string(),
            pattern: r"^\(This file must be converted with BinHex 4.0\)$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 1.0,
            common_name: Some("binhex".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Web & DNS Encodings ---
        Signature {
            name: "Quoted-Printable".to_string(),
            description: "MIME Quoted-Printable encoding".to_string(),
            pattern: r"^(?:[!-<>-~]|=[\dA-F]{2}|\r\n)*$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.3,
            common_name: Some("quoted-printable".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Punycode".to_string(),
            description: "Internationalized Domain Names (IDNA)".to_string(),
            pattern: r"^xn--[A-Za-z0-9\-]+$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 1.0,
            common_name: Some("punycode".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Classical & Educational ---
        Signature {
            name: "ROT47".to_string(),
            description: "Shift cipher for ASCII characters 33-126".to_string(),
            pattern: r"^[!-~]+$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.1,
            common_name: Some("rot47".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Atbash".to_string(),
            description: "Alphabet reversal substitution".to_string(),
            pattern: r"^[A-Za-z\s]+$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.1,
            common_name: Some("atbash".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Baconian Cipher".to_string(),
            description: "Francis Bacon's steganographic cipher".to_string(),
            pattern: r"^[ABab\s]{5,}+$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.3,
            common_name: Some("bacon".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Specialized & Niche Encodings ---
        Signature {
            name: "EBCDIC (Standard)".to_string(),
            description: "Extended Binary Coded Decimal Interchange Code".to_string(),
            pattern: r"^[\x00-\xFF]+$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.05, // Impossible to detect reliably without freq analysis
            common_name: Some("ebcdic".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Baudot Code".to_string(),
            description: "5-bit character set (ITA2)".to_string(),
            pattern: r"^[A-Z0-9\s.,?!/-]+$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.1,
            common_name: Some("baudot".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Protobuf (Hex-encoded heuristic)".to_string(),
            description: "Potential Protocol Buffer binary stream".to_string(),
            pattern: r"^(?:[0-9a-f]{2})*(?:08|10|18|20|28|30|38)[0-9a-f]+$".to_string(),
            detection_type: DetectionType::Encoding,
            confidence_weight: 0.2,
            common_name: Some("protobuf".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Statistical Cipher Heuristics ---
        Signature {
            name: "Playfair Cipher (Heuristic)".to_string(),
            description: "Digraph substitution cipher".to_string(),
            pattern: r"^[A-Z\s]{20,}+$".to_string(),
            detection_type: DetectionType::Cipher,
            confidence_weight: 0.1,
            common_name: Some("playfair".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Nihilist Cipher (Heuristic)".to_string(),
            description: "Polybius square based cipher".to_string(),
            pattern: r"^[0-9\s]{20,}+$".to_string(),
            detection_type: DetectionType::Cipher,
            confidence_weight: 0.1,
            common_name: Some("nihilist".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
    ]
}
