use crate::core::patterns::{Signature, DetectionType, SecurityRating};

pub fn get_hash_signatures() -> Vec<Signature> {
    vec![
        // --- MDC Family ---
        Signature {
            name: "MD2".to_string(),
            description: "Message-Digest Algorithm 2".to_string(),
            pattern: r"^[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.3,
            common_name: Some("md2".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MD4".to_string(),
            description: "Message-Digest Algorithm 4".to_string(),
            pattern: r"^[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.4,
            common_name: Some("md4".to_string()),
            hashcat_mode: Some(900),
            john_format: Some("raw-md4".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MD5".to_string(),
            description: "Message-Digest Algorithm 5".to_string(),
            pattern: r"^[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9,
            common_name: Some("md5".to_string()),
            hashcat_mode: Some(0),
            john_format: Some("raw-md5".to_string()),
            security_rating: Some(SecurityRating::Broken),
            compliance_refs: vec!["PCI DSS 4.0".to_string(), "NIST SP 800-131A".to_string()],
            parameters: vec![],
        },
        // --- SHA Family ---
        Signature {
            name: "SHA-0".to_string(),
            description: "Secure Hash Algorithm 0".to_string(),
            pattern: r"^[a-fA-F0-9]{40}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.1,
            common_name: None,
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA-1".to_string(),
            description: "Secure Hash Algorithm 1".to_string(),
            pattern: r"^[a-fA-F0-9]{40}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.95,
            common_name: Some("sha1".to_string()),
            hashcat_mode: Some(100),
            john_format: Some("raw-sha1".to_string()),
            security_rating: Some(SecurityRating::Broken),
            compliance_refs: vec!["NIST FIPS 180-4".to_string()],
            parameters: vec![],
        },
        Signature {
            name: "SHA-224".to_string(),
            description: "Secure Hash Algorithm 224-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{56}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.98,
            common_name: Some("sha224".to_string()),
            hashcat_mode: Some(1300),
            john_format: Some("raw-sha224".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA-256".to_string(),
            description: "Secure Hash Algorithm 256-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.98,
            common_name: Some("sha256".to_string()),
            hashcat_mode: Some(1400),
            john_format: Some("raw-sha256".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA-384".to_string(),
            description: "Secure Hash Algorithm 384-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{96}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.98,
            common_name: Some("sha384".to_string()),
            hashcat_mode: Some(10800),
            john_format: Some("raw-sha384".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA-512".to_string(),
            description: "Secure Hash Algorithm 512-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{128}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.99,
            common_name: Some("sha512".to_string()),
            hashcat_mode: Some(1700),
            john_format: Some("raw-sha512".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- SHA-3 Family & Keccak ---
        Signature {
            name: "SHA3-224".to_string(),
            description: "SHA-3 (Keccak) 224-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{56}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.8,
            common_name: Some("sha3-224".to_string()),
            hashcat_mode: Some(17300),
            john_format: Some("raw-sha3-224".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA3-256".to_string(),
            description: "SHA-3 (Keccak) 256-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.85,
            common_name: Some("sha3-256".to_string()),
            hashcat_mode: Some(17400),
            john_format: Some("raw-sha3-256".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA3-384".to_string(),
            description: "SHA-3 (Keccak) 384-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{96}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.85,
            common_name: Some("sha3-384".to_string()),
            hashcat_mode: Some(17500),
            john_format: Some("raw-sha3-384".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA3-512".to_string(),
            description: "SHA-3 (Keccak) 512-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{128}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9,
            common_name: Some("sha3-512".to_string()),
            hashcat_mode: Some(17600),
            john_format: Some("raw-sha3-512".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Keccak-256".to_string(),
            description: "Keccak-256 (Ethereum)".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.7, // Heavy overlap with SHA3-256
            common_name: Some("keccak256".to_string()),
            hashcat_mode: Some(17700),
            john_format: Some("raw-keccak-256".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- BLAKE Family ---
        Signature {
            name: "BLAKE2b-512".to_string(),
            description: "BLAKE2b (512-bit output)".to_string(),
            pattern: r"^[a-fA-F0-9]{128}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.8,
            common_name: Some("blake2b-512".to_string()),
            hashcat_mode: Some(600),
            john_format: Some("raw-blake2b".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "BLAKE2s-256".to_string(),
            description: "BLAKE2s (256-bit output)".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.8,
            common_name: Some("blake2s-256".to_string()),
            hashcat_mode: Some(610),
            john_format: Some("raw-blake2s".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "BLAKE3".to_string(),
            description: "BLAKE3 extremely fast hash".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.6,
            common_name: Some("blake3".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- RIPEMD Family ---
        Signature {
            name: "RIPEMD-128".to_string(),
            description: "RIPE Message Digest 128-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.7,
            common_name: Some("ripemd128".to_string()),
            hashcat_mode: Some(9000),
            john_format: Some("ripemd-128".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "RIPEMD-160".to_string(),
            description: "RIPE Message Digest 160-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{40}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.7,
            common_name: Some("ripemd160".to_string()),
            hashcat_mode: Some(6000),
            john_format: Some("ripemd-160".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "RIPEMD-256".to_string(),
            description: "RIPE Message Digest 256-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.7,
            common_name: Some("ripemd256".to_string()),
            hashcat_mode: None,
            john_format: Some("ripemd-256".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "RIPEMD-320".to_string(),
            description: "RIPE Message Digest 320-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{80}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.7,
            common_name: Some("ripemd320".to_string()),
            hashcat_mode: None,
            john_format: Some("ripemd-320".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Whirlpool ---
        Signature {
            name: "Whirlpool".to_string(),
            description: "Whirlpool cryptographic hash function".to_string(),
            pattern: r"^[a-fA-F0-9]{128}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.8,
            common_name: Some("whirlpool".to_string()),
            hashcat_mode: Some(6100),
            john_format: Some("whirlpool".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- GOST Family ---
        Signature {
            name: "GOST R 34.11-94".to_string(),
            description: "GOST R 34.11-94 (Russian standard)".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.6,
            common_name: Some("gost-94".to_string()),
            hashcat_mode: Some(6900),
            john_format: Some("gost".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Streebog-256".to_string(),
            description: "GOST R 34.11-2012 (Streebog) 256-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.6,
            common_name: Some("streebog256".to_string()),
            hashcat_mode: Some(11700),
            john_format: Some("streebog-256".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Streebog-512".to_string(),
            description: "GOST R 34.11-2012 (Streebog) 512-bit".to_string(),
            pattern: r"^[a-fA-F0-9]{128}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.6,
            common_name: Some("streebog512".to_string()),
            hashcat_mode: Some(11800),
            john_format: Some("streebog-512".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Tiger ---
        Signature {
            name: "Tiger-192".to_string(),
            description: "Tiger hash function (192-bit)".to_string(),
            pattern: r"^[a-fA-F0-9]{48}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.7,
            common_name: Some("tiger192".to_string()),
            hashcat_mode: None,
            john_format: Some("tiger".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Other Cryptographic Hashes ---
        Signature {
            name: "SM3".to_string(),
            description: "SM3 (Chinese standard hash)".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.6,
            common_name: Some("sm3".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Modern Password KDFs ---
        Signature {
            name: "Argon2".to_string(),
            description: "Argon2 password hash (i/d/id)".to_string(),
            pattern: r"^\$(?P<variant>argon2[di]d?)\$v=(?P<version>\d+)\$m=(?P<memory>\d+),t=(?P<time>\d+),p=(?P<parallelism>\d+)\$(?P<salt>[./A-Za-z0-9]+)\$(?P<hash>[./A-Za-z0-9]+)$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("argon2".to_string()),
            hashcat_mode: Some(11900),
            john_format: Some("argon2".to_string()),
            security_rating: Some(SecurityRating::Secure),
            compliance_refs: vec!["OWASP Password Storage".to_string()],
            parameters: vec!["variant".to_string(), "version".to_string(), "memory".to_string(), "time".to_string(), "parallelism".to_string(), "salt".to_string(), "hash".to_string()],
        },
        Signature {
            name: "BCrypt".to_string(),
            description: "Blowfish-based password hash".to_string(),
            pattern: r"^\$(?P<version>2[ayb]?)\$(?P<cost>[0-9]{2})\$(?P<salt>[./A-Za-z0-9]{22})(?P<hash>[./A-Za-z0-9]{31})$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("bcrypt".to_string()),
            hashcat_mode: Some(3200),
            john_format: Some("bf".to_string()),
            security_rating: Some(SecurityRating::Secure),
            compliance_refs: vec!["NIST SP 800-63B".to_string()],
            parameters: vec!["version".to_string(), "cost".to_string(), "salt".to_string(), "hash".to_string()],
        },
        Signature {
            name: "Scrypt".to_string(),
            description: "Scrypt key derivation function".to_string(),
            pattern: r"^\$7\$[./A-Za-z0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9,
            common_name: Some("scrypt".to_string()),
            hashcat_mode: Some(8900),
            john_format: Some("scrypt".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Unix & Linux Password Hashes ---
        Signature {
            name: "Unix Crypt (DES)".to_string(),
            description: "Traditional Unix crypt(3)".to_string(),
            pattern: r"^[./A-Za-z0-9]{13}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9,
            common_name: Some("descrypt".to_string()),
            hashcat_mode: Some(1500),
            john_format: Some("descrypt".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MD5crypt".to_string(),
            description: "MD5-based Unix crypt".to_string(),
            pattern: r"^\$1\$[./A-Za-z0-9]{8}\$[./A-Za-z0-9]{22}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("md5crypt".to_string()),
            hashcat_mode: Some(500),
            john_format: Some("md5crypt".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA256crypt".to_string(),
            description: "SHA256-based Unix crypt".to_string(),
            pattern: r"^\$5\$(?:rounds=\d+\$)?[./A-Za-z0-9]{1,16}\$[./A-Za-z0-9]{43}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("sha256crypt".to_string()),
            hashcat_mode: Some(7400),
            john_format: Some("sha256crypt".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SHA512crypt".to_string(),
            description: "SHA512-based Unix crypt".to_string(),
            pattern: r"^\$6\$(?:rounds=\d+\$)?[./A-Za-z0-9]{1,16}\$[./A-Za-z0-9]{86}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("sha512crypt".to_string()),
            hashcat_mode: Some(1800),
            john_format: Some("sha512crypt".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Windows Password Hashes ---
        Signature {
            name: "NTLM".to_string(),
            description: "Windows NT LAN Manager hash".to_string(),
            pattern: r"^[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.6,
            common_name: Some("ntlm".to_string()),
            hashcat_mode: Some(1000),
            john_format: Some("nt".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "NetNTLMv1 / ESS".to_string(),
            description: "Windows network authentication v1".to_string(),
            pattern: r"^[^\:]+\:[^\:]*\:[a-fA-F0-9]{16}\:[a-fA-F0-9]{48}\:[a-fA-F0-9]{48}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9,
            common_name: Some("netntlmv1".to_string()),
            hashcat_mode: Some(5500),
            john_format: Some("netntlm".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "NetNTLMv2".to_string(),
            description: "Windows network authentication v2".to_string(),
            pattern: r"^[^\:]+\:[^\:]*\:[a-fA-F0-9]{16}\:[a-fA-F0-9]{32}\:[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9,
            common_name: Some("netntlmv2".to_string()),
            hashcat_mode: Some(5600),
            john_format: Some("netntlmv2".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MS-Cash / DCC1".to_string(),
            description: "Windows Domain Cached Credentials v1".to_string(),
            pattern: r"^[A-Za-z0-9_.-]+\#[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.8,
            common_name: Some("mscash".to_string()),
            hashcat_mode: Some(1100),
            john_format: Some("mscash".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MS-Cash2 / DCC2".to_string(),
            description: "Windows Domain Cached Credentials v2".to_string(),
            pattern: r"^\$DCC2\$\d+\#[^\#]+\#[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("mscash2".to_string()),
            hashcat_mode: Some(2100),
            john_format: Some("mscash2".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Cisco Family ---
        Signature {
            name: "Cisco Type 4".to_string(),
            description: "Cisco IOS SHA256 hashing".to_string(),
            pattern: r"^\$4\$[./A-Za-z0-9]{43}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("cisco-type4".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Cisco Type 5".to_string(),
            description: "Cisco local salted MD5".to_string(),
            pattern: r"^\$1\$[./A-Za-z0-9]{4}\$[./A-Za-z0-9]{22}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("cisco-type5".to_string()),
            hashcat_mode: Some(500),
            john_format: Some("md5crypt".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Cisco Type 7".to_string(),
            description: "Cisco vigenere-based obfuscation".to_string(),
            pattern: r"^[0-9]{2}[0-9A-Fa-f]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.5,
            common_name: Some("cisco-type7".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Cisco Type 8 / 9".to_string(),
            description: "Cisco PBKDF2 / Scrypt".to_string(),
            pattern: r"^\$[89]\$[./A-Za-z0-9]{1,16}\$[./A-Za-z0-9]{43}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("cisco-type8".to_string()),
            hashcat_mode: Some(9200),
            john_format: Some("cisco8".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Enterprise & Network ---
        Signature {
            name: "Kerberos 5 TGS-REP etype 23".to_string(),
            description: "Kerberos RC4-HMAC ticket".to_string(),
            pattern: r"^\$krb5tgs\$23\$\*[^\*]*\*[^\*]*\*[^\*]*\$[a-fA-F0-9]{32}\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("krb5tgs".to_string()),
            hashcat_mode: Some(13100),
            john_format: Some("krb5tgs".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "WPA-PSK / WPA2-PSK".to_string(),
            description: "WIFI password hash (PMK)".to_string(),
            pattern: r"^[a-fA-F0-9]{64}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.3, // Overlaps with SHA256
            common_name: Some("wpa".to_string()),
            hashcat_mode: Some(2500),
            john_format: Some("wpapsk".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Blockchain & Crypto ---
        Signature {
            name: "Bitcoin Address (Base58Check)".to_string(),
            description: "Legacy Bitcoin address (P2PKH)".to_string(),
            pattern: r"^1[1-9A-HJ-NP-Za-km-z]{25,34}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("bitcoin-addr".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Ethereum Address".to_string(),
            description: "Ethereum wallet address (Hex)".to_string(),
            pattern: r"^0x[a-fA-F0-9]{40}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("eth-addr".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Bitcoin WIF".to_string(),
            description: "Wallet Import Format (Private Key)".to_string(),
            pattern: r"^[5KL][1-9A-HJ-NP-Za-km-z]{50,51}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("wif".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- CMS & Web Frameworks ---
        Signature {
            name: "Drupal 7+".to_string(),
            description: "Drupal 7/8/9 password hash".to_string(),
            pattern: r"^\$S\$[./A-Za-z0-9]{52}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("drupal7".to_string()),
            hashcat_mode: Some(7900),
            john_format: Some("drupal7".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Joomla < 2.5.18".to_string(),
            description: "Joomla MD5 salted hash".to_string(),
            pattern: r"^[a-fA-F0-9]{32}:[./A-Za-z0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("joomla".to_string()),
            hashcat_mode: Some(11),
            john_format: Some("joomla".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "vBulletin < 3.8.5".to_string(),
            description: "vBulletin MD5 salted hash".to_string(),
            pattern: r"^[a-fA-F0-9]{32}:[./A-Za-z0-9]{30}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("vbulletin".to_string()),
            hashcat_mode: Some(2611),
            john_format: Some("vbulletin".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Legacy & Misc ---
        Signature {
            name: "MSSQL 2000".to_string(),
            description: "Microsoft SQL Server 2000 hash".to_string(),
            pattern: r"^0x0100[a-fA-F0-9]{8}[a-fA-F0-9]{40}[a-fA-F0-9]{40}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("mssql2000".to_string()),
            hashcat_mode: Some(131),
            john_format: Some("mssql".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MSSQL 2005".to_string(),
            description: "Microsoft SQL Server 2005 hash".to_string(),
            pattern: r"^0x0100[a-fA-F0-9]{8}[a-fA-F0-9]{40}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("mssql2005".to_string()),
            hashcat_mode: Some(132),
            john_format: Some("mssql05".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MSSQL 2012 / 2014".to_string(),
            description: "Microsoft SQL Server 2012/2014 hash".to_string(),
            pattern: r"^0x0200[a-fA-F0-9]{8}[a-fA-F0-9]{128}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("mssql2012".to_string()),
            hashcat_mode: Some(1731),
            john_format: Some("mssql12".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Database Hashes ---
        Signature {
            name: "MySQL < 4.1".to_string(),
            description: "Old MySQL unsalted hash".to_string(),
            pattern: r"^[a-f0-9]{16}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.2, // Very short, overlaps
            common_name: Some("mysql-old".to_string()),
            hashcat_mode: Some(200),
            john_format: Some("mysql".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "MySQL 4.1+ / MySQL 5".to_string(),
            description: "SHA-1(SHA-1(password))".to_string(),
            pattern: r"^\*[a-fA-F0-9]{40}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("mysql-sha1".to_string()),
            hashcat_mode: Some(300),
            john_format: Some("mysql-sha1".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "PostgreSQL".to_string(),
            description: "Postgres MD5(password + user)".to_string(),
            pattern: r"^md5[a-fA-F0-9]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("postgres".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Oracle 7-10g".to_string(),
            description: "Oracle DES-based hash".to_string(),
            pattern: r"^[a-fA-F0-9]{16}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.2,
            common_name: Some("oracle7".to_string()),
            hashcat_mode: Some(3100),
            john_format: Some("oracle".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Oracle 11g / 12c".to_string(),
            description: "Oracle SHA1-based salted hash".to_string(),
            pattern: r"^S:[A-Z0-9]{60}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("oracle11".to_string()),
            hashcat_mode: Some(112),
            john_format: Some("oracle11".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Web Frameworks & CMS ---
        Signature {
            name: "WordPress / phpBB (phpass)".to_string(),
            description: "Portable hash (MD5-based)".to_string(),
            pattern: r"^\$P\$[./A-Za-z0-9]{31}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("phpass".to_string()),
            hashcat_mode: Some(400),
            john_format: Some("phpass".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Django PBKDF2-SHA256".to_string(),
            description: "Django framework default hash".to_string(),
            pattern: r"^pbkdf2_sha256\$\d+\$[A-Za-z0-9+/]+\$[A-Za-z0-9+/=]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("django".to_string()),
            hashcat_mode: Some(10000),
            john_format: Some("django".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Magento 2 (SHA-256)".to_string(),
            description: "Magento 2 salted SHA-256".to_string(),
            pattern: r"^[a-fA-F0-9]{64}:[A-Za-z0-9+/]{32}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("magento2".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Ruby on Rails (Devise)".to_string(),
            description: "Rails BCrypt-based devise hash".to_string(),
            pattern: r"^\$2[ayb]\$[0-9]{2}\$[./A-Za-z0-9]{53}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9, // Overlaps with BCrypt
            common_name: Some("rails-devise".to_string()),
            hashcat_mode: Some(3200),
            john_format: Some("bf".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Enterprise & OS ---
        Signature {
            name: "IBM RACF".to_string(),
            description: "IBM Mainframe password hash".to_string(),
            pattern: r"^[A-Z0-9]{16}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.1, // High collision
            common_name: Some("racf".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "AIX {smd5}".to_string(),
            description: "AIX salted MD5 hash".to_string(),
            pattern: r"^\{smd5\}[./A-Za-z0-9]{8}\$[./A-Za-z0-9]{22}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("aix-smd5".to_string()),
            hashcat_mode: Some(6300),
            john_format: Some("aix-smd5".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "AIX {ssha1}".to_string(),
            description: "AIX salted SHA1 hash".to_string(),
            pattern: r"^\{ssha1\}[./A-Za-z0-9]{8}\$[./A-Za-z0-9]{28}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("aix-ssha1".to_string()),
            hashcat_mode: Some(6700),
            john_format: Some("aix-ssha1".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "macOS v10.7 (Salted SHA512)".to_string(),
            description: "Legacy macOS password hash".to_string(),
            pattern: r"^[a-fA-F0-9]{136}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("macosx-sha512".to_string()),
            hashcat_mode: Some(1722),
            john_format: Some("xsha-512".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Juniper Netscreen / ScreenOS".to_string(),
            description: "Juniper local password hash".to_string(),
            pattern: r"^[A-Za-z0-9]{30}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.8,
            common_name: Some("juniper".to_string()),
            hashcat_mode: Some(22),
            john_format: Some("juniper".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Fortigate (Type 6)".to_string(),
            description: "Fortinet Type 6 encryption".to_string(),
            pattern: r"^AK1[A-Za-z0-9+/]{27}$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("fortigate".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Full-Disk Encryption ---
        Signature {
            name: "BitLocker".to_string(),
            description: "Windows BitLocker encryption hash".to_string(),
            pattern: r"^\$bitlocker\$[0-9]\$[0-9]+\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("bitlocker".to_string()),
            hashcat_mode: Some(22100),
            john_format: Some("bitlocker".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "LUKS / LUKS2".to_string(),
            description: "Linux Unified Key Setup".to_string(),
            pattern: r"^\$luks\$[0-9]\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("luks".to_string()),
            hashcat_mode: Some(14600),
            john_format: Some("luks".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Apple FileVault 2".to_string(),
            description: "macOS full-disk encryption".to_string(),
            pattern: r"^\$fv2\$[0-9]+\$[a-fA-F0-9]{32}\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("filevault2".to_string()),
            hashcat_mode: Some(18300),
            john_format: Some("filevault2".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Password Managers ---
        Signature {
            name: "KeePass (KDBX)".to_string(),
            description: "KeePass Password Manager database".to_string(),
            pattern: r"^\$keepass\$[0-9]\$[0-9]+\$[0-9]+\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("keepass".to_string()),
            hashcat_mode: Some(13400),
            john_format: Some("keepass".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "1Password (Cloud)".to_string(),
            description: "1Password cloud-based vault".to_string(),
            pattern: r"^\$1password\$[0-9]\$[a-zA-Z0-9+/=]+\$[a-zA-Z0-9+/=]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("1password".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "LastPass".to_string(),
            description: "LastPass vault hash".to_string(),
            pattern: r"^[a-fA-F0-9]{64}:[a-zA-Z0-9._-]+:[0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 0.9,
            common_name: Some("lastpass".to_string()),
            hashcat_mode: Some(6800),
            john_format: Some("lastpass".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Forensic Artifacts ---
        Signature {
            name: "Android Backup (V4)".to_string(),
            description: "Android encrypted backup format".to_string(),
            pattern: r"^\$androidbackup\$[0-9]\$[0-9]+\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("android-backup".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "iOS Backup (V1-V4)".to_string(),
            description: "Apple iTunes backup encryption".to_string(),
            pattern: r"^\$itunes_backup\$[0-9]\*[a-fA-F0-9]+\*[0-9]+\*[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("itunes-backup".to_string()),
            hashcat_mode: Some(14700),
            john_format: Some("itunes-backup".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "WhatsApp Database".to_string(),
            description: "WhatsApp encrypted database (crypt12/14/15)".to_string(),
            pattern: r"^\$whatsapp\$[0-9]+\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("whatsapp".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Crypto Wallets ---
        Signature {
            name: "MetaMask Vault".to_string(),
            description: "MetaMask browser extension wallet".to_string(),
            pattern: r"^\$metamask\$[0-9]+\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("metamask".to_string()),
            hashcat_mode: None,
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Electrum Wallet (Seed/Private Key)".to_string(),
            description: "Electrum Bitcoin wallet".to_string(),
            pattern: r"^\$electrum\$[0-9]\*[a-fA-F0-9]+\*[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("electrum".to_string()),
            hashcat_mode: Some(16600),
            john_format: Some("electrum".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "Bitcoin Core (wallet.dat)".to_string(),
            description: "Bitcoin-Qt / Bitcoin Core wallet".to_string(),
            pattern: r"^\$bitcoin\$[0-9]+\$[a-fA-F0-9]+\$[0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("bitcoin-core".to_string()),
            hashcat_mode: Some(11300),
            john_format: Some("bitcoin".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- Network Protocols & IoT ---
        Signature {
            name: "EAP-MD5 / CHAP".to_string(),
            description: "Extensible Authentication Protocol MD5".to_string(),
            pattern: r"^\$chap\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("chap".to_string()),
            hashcat_mode: Some(7),
            john_format: None,
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "SNMPv3".to_string(),
            description: "SNMPv3 USM authentication".to_string(),
            pattern: r"^\$snmpv3\$[0-9]\$[a-fA-F0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("snmpv3".to_string()),
            hashcat_mode: Some(140),
            john_format: Some("snmpv3".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        // --- SSH / PGP / GPG ---
        Signature {
            name: "SSH Private Key (Encrypted)".to_string(),
            description: "Encrypted OpenSSH / RSA key".to_string(),
            pattern: r"^\$pkcs8\$[0-9]\$[0-9]+\$[a-zA-Z0-9+/=]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("ssh-key".to_string()),
            hashcat_mode: Some(22911),
            john_format: Some("ssh".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
        Signature {
            name: "GPG / PGP Private Key".to_string(),
            description: "GNU Privacy Guard private key".to_string(),
            pattern: r"^\$gpg\$[0-9]\$[0-9]+\$[0-9]+\$[a-fA-F0-9]+$".to_string(),
            detection_type: DetectionType::Hash,
            confidence_weight: 1.0,
            common_name: Some("gpg".to_string()),
            hashcat_mode: None,
            john_format: Some("gpg".to_string()),
            security_rating: None,
            compliance_refs: vec![],
            parameters: vec![],
        },
    ]
}
