use super::{BytePattern, CarveProfile};

pub fn builtin_profiles() -> Vec<CarveProfile> {
    vec![
        CarveProfile {
            extension: "jpg".to_string(),
            description: "JPEG Image".to_string(),
            headers: vec![BytePattern::exact(&[0xFF, 0xD8, 0xFF])],
            footer: Some(BytePattern::exact(&[0xFF, 0xD9])),
            max_size: Some(20 * 1024 * 1024),
        },
        CarveProfile {
            extension: "png".to_string(),
            description: "PNG Image".to_string(),
            headers: vec![BytePattern::exact(b"\x89PNG\r\n\x1a\n")],
            footer: Some(BytePattern::exact(b"\x00\x00\x00\x00IEND\xAE\x42\x60\x82")),
            max_size: Some(20 * 1024 * 1024),
        },
        CarveProfile {
            extension: "gif".to_string(),
            description: "GIF Image".to_string(),
            headers: vec![BytePattern::exact(b"GIF87a"), BytePattern::exact(b"GIF89a")],
            footer: Some(BytePattern::exact(&[0x3B])),
            max_size: Some(20 * 1024 * 1024),
        },
        CarveProfile {
            extension: "bmp".to_string(),
            description: "Bitmap Image".to_string(),
            headers: vec![BytePattern::exact(b"BM")],
            footer: None,
            max_size: Some(16 * 1024 * 1024),
        },
        CarveProfile {
            extension: "pdf".to_string(),
            description: "PDF Document".to_string(),
            headers: vec![BytePattern::exact(b"%PDF-")],
            footer: Some(BytePattern::exact(b"%%EOF")),
            max_size: Some(64 * 1024 * 1024),
        },
        CarveProfile {
            extension: "zip".to_string(),
            description: "ZIP Archive".to_string(),
            headers: vec![
                BytePattern::exact(b"PK\x03\x04"),
                BytePattern::exact(b"PK\x05\x06"),
                BytePattern::exact(b"PK\x07\x08"),
            ],
            footer: None,
            max_size: Some(256 * 1024 * 1024),
        },
        CarveProfile {
            extension: "rar".to_string(),
            description: "RAR Archive".to_string(),
            headers: vec![
                BytePattern::exact(b"Rar!\x1A\x07\x00"),
                BytePattern::exact(b"Rar!\x1A\x07\x01\x00"),
            ],
            footer: None,
            max_size: Some(256 * 1024 * 1024),
        },
        CarveProfile {
            extension: "7z".to_string(),
            description: "7z Archive".to_string(),
            headers: vec![BytePattern::exact(&[0x37, 0x7A, 0xBC, 0xAF, 0x27, 0x1C])],
            footer: None,
            max_size: Some(256 * 1024 * 1024),
        },
        CarveProfile {
            extension: "gz".to_string(),
            description: "Gzip Stream".to_string(),
            headers: vec![BytePattern::exact(&[0x1F, 0x8B, 0x08])],
            footer: None,
            max_size: Some(128 * 1024 * 1024),
        },
        CarveProfile {
            extension: "sqlite".to_string(),
            description: "SQLite Database".to_string(),
            headers: vec![BytePattern::exact(b"SQLite format 3\x00")],
            footer: None,
            max_size: Some(512 * 1024 * 1024),
        },
        CarveProfile {
            extension: "elf".to_string(),
            description: "ELF Binary".to_string(),
            headers: vec![BytePattern::exact(b"\x7FELF")],
            footer: None,
            max_size: Some(128 * 1024 * 1024),
        },
        CarveProfile {
            extension: "exe".to_string(),
            description: "PE Executable".to_string(),
            headers: vec![BytePattern::exact(b"MZ")],
            footer: None,
            max_size: Some(128 * 1024 * 1024),
        },
        CarveProfile {
            extension: "macho".to_string(),
            description: "Mach-O Binary".to_string(),
            headers: vec![
                BytePattern::exact(&[0xFE, 0xED, 0xFA, 0xCE]),
                BytePattern::exact(&[0xCE, 0xFA, 0xED, 0xFE]),
                BytePattern::exact(&[0xFE, 0xED, 0xFA, 0xCF]),
                BytePattern::exact(&[0xCF, 0xFA, 0xED, 0xFE]),
            ],
            footer: None,
            max_size: Some(128 * 1024 * 1024),
        },
        CarveProfile {
            extension: "ole".to_string(),
            description: "OLE Compound Document".to_string(),
            headers: vec![BytePattern::exact(&[
                0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1,
            ])],
            footer: None,
            max_size: Some(256 * 1024 * 1024),
        },
        CarveProfile {
            extension: "wav".to_string(),
            description: "WAVE Audio".to_string(),
            headers: vec![BytePattern::wildcard(vec![
                Some(b'R'),
                Some(b'I'),
                Some(b'F'),
                Some(b'F'),
                None,
                None,
                None,
                None,
                Some(b'W'),
                Some(b'A'),
                Some(b'V'),
                Some(b'E'),
            ])],
            footer: None,
            max_size: Some(256 * 1024 * 1024),
        },
        CarveProfile {
            extension: "avi".to_string(),
            description: "AVI Video".to_string(),
            headers: vec![BytePattern::wildcard(vec![
                Some(b'R'),
                Some(b'I'),
                Some(b'F'),
                Some(b'F'),
                None,
                None,
                None,
                None,
                Some(b'A'),
                Some(b'V'),
                Some(b'I'),
                Some(b' '),
            ])],
            footer: None,
            max_size: Some(1024 * 1024 * 1024),
        },
        CarveProfile {
            extension: "mov".to_string(),
            description: "QuickTime or MP4 Container".to_string(),
            headers: vec![BytePattern::wildcard(vec![
                None,
                None,
                None,
                None,
                Some(b'f'),
                Some(b't'),
                Some(b'y'),
                Some(b'p'),
            ])],
            footer: None,
            max_size: Some(1024 * 1024 * 1024),
        },
        CarveProfile {
            extension: "mpg".to_string(),
            description: "MPEG Program Stream".to_string(),
            headers: vec![BytePattern::exact(&[0x00, 0x00, 0x01, 0xBA])],
            footer: None,
            max_size: Some(1024 * 1024 * 1024),
        },
        CarveProfile {
            extension: "wmv".to_string(),
            description: "ASF or WMV Container".to_string(),
            headers: vec![BytePattern::exact(&[
                0x30, 0x26, 0xB2, 0x75, 0x8E, 0x66, 0xCF, 0x11, 0xA6, 0xD9, 0x00, 0xAA, 0x00, 0x62,
                0xCE, 0x6C,
            ])],
            footer: None,
            max_size: Some(1024 * 1024 * 1024),
        },
    ]
}
